---
abstract: 'The Acmeist Module Package Management Tool'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Package
name: Package
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Hash::Merge: 0.12
  IO::All: 0.44
  Mouse: 0.97
  MouseX::App::Cmd: 0.08
  Template::Toolkit::Simple: 0.14
  YAML::XS: 0.37
  perl: 5.8.3
resources:
  homepage: https://github.com/ingydotnet/package-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/package-pm.git
    web: https://github.com/ingydotnet/package-pm/tree
version: 0.17
